### ISSUE TITLE
avahi missing

### ISSUE THREAD

**Issue by bjwelker** [m-kloeckner/snapcast-tcz#3]
I dunno how you do that but i can´t load avahi for picore the tcz is missing in the repo

**Comment by m-kloeckner** [comment]
I used a modified image from https://sites.google.com/site/picoreplayer/home
I guess AVAHI is included there... But I see you managed to make it run on any PiCore version?

**Comment by bjwelker** [comment]
Yeah i search the way picoreplayer got it running.
It now runs on the normal piCore image to. So no overhang from picoreplayer. A better webinterface with sound output switching is now on the list ...

**Comment by gartensofa** [comment]
is it possible that they kicked avahi out of the picoreplayer?
tce-loading it gives a 404:
`tc@piCorePlayer:~$ tce-load -wi avahi
Downloading: avahi.tcz
Connecting to distro.ibiblio.org (152.19.134.43:80)
wget: server returned error: HTTP/1.1 404 Not Found
md5sum: avahi.tcz.md5.txt: No such file or directory
Error on avahi.tcz`

and downloading the dependencies as suggested returns a 400:
tc@piCorePlayer:~$ wget http://ralph_irving.users.sourceforge.net/pico/avahi.tcz /mnt/mmcblk0p2/tce/optional/
Connecting to ralph_irving.users.sourceforge.net (216.34.181.96:80)
wget: server returned error: HTTP/1.1 400 Bad Request

Any tips to get this running would be greatly appreciated.

Edit: I'm working on a raspi zero 1.3
