### ISSUE TITLE
how to update snapcast

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [m-kloeckner/snapcast-tcz#6]
Hey, thanks for this implementation. I think tinycore is actually the best system to run the snapclient. 
Could you perhaps shed some light on how I would upgrade this tcz file to snapclient 0.7? Can I just exchange the binary at some point?

**Comment by m-kloeckner** [comment]
Hey! Actually you could just replace the binary in snapcast-tcz/tcz/usr/local/sbin/with the 0.7 binary and then run `mksquashfs tcz snapclient.tcz` in the snapcast-tcz Folder to build the new package.
However, I don't know if the makefile is still valid for the 0.7 release. So you might need to make some adjustments there to build a static binary for tinycore.

I am currently on vacation. I can update the git to work with 0.7 when I am back.

**Comment by 1337sup3rh4x0r** [comment]
Thanks for the quick answer. I plan to give snapcast a try over the weekend so I figured starting with the latest version would be nice. I'll see if I can handle the upgrade myself :)

By the way: When snapclient runs alongside picoreplayer, how is the alsa output handled when both play at the same time? dmix or does one playback stop?

**Comment by 1337sup3rh4x0r** [comment]
I failed compiling 0.7.
Do I replace the Makefile within the top level snapcast folder or the one in the client folder?
U back from vacation yet? :)

**Comment by m-kloeckner** [comment]
I just updated the repository fpr v0.7. Please check it out!

Unfortunately I do not use snapclient on PiCore anymore. I replaced the Raspberries with TP-Link WR710N's running OpenWRT. (Really recommended by the way.) So I couldn't really test. But it should work just fine.

Actually the Makefile was still valid, so replacing the Makefile in the client folder with the one from here should have worked.

**Comment by 1337sup3rh4x0r** [comment]
Thank you for updating this even though you don't use it anymore. The WR710N looks really interesting from  a price POV plus it doesn't require all the extras (case, power supply,...) like a raspy. Will any cheap USB DAC work with it?
