### ISSUE TITLE
how to change audio output

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [m-kloeckner/snapcast-tcz#7]
Hi, me again :)

I would like to make snapclient use a different soundcard via the -s option. In Debian this is usually added to the file `/lib/systemd/system/snapclient.service`. Where do I put it In tinycore?  I can't edit `/use/share/etc/init.d/snapclient` as it is read only.

**Comment by m-kloeckner** [comment]
Hi! Well there are two options:
a) If I remember correctly, you have to make the changes in the /opt folder and then store the changes via `sudo filetool.sh -b`. Check if you can find the init script in /opt.
b) You clone my repository, change the file `tcz/usr/local/etc/init.d/snapclient` accordingly and then rebuild the package with these adjustments included: `mksquashfs tcz snapclient.tcz`.

**Comment by 1337sup3rh4x0r** [comment]
Thanks!
Unfortunately the init script is not in /opt/

I now solved it by replacing the startup line in /opt/bootlocal.sh:

```
#/usr/local/etc/init.d/snapclient start
snapclient -s 2
```
